export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_AUTO_LOGIN = "AUTH_AUTO_LOGIN";

export const PAPER_CREATED = "PAPER_CREATED";
export const PAPER_IS_CREATING = "PAPER_IS_CREATING";
export const PAPER_CREATED_2 = "PAPER_CREATED_2";
export const PAPER_IS_CREATING_2 = "PAPER_IS_CREATING_2";
export const PAPER_CREATED_3 = "PAPER_CREATED_3";
export const PAPER_IS_CREATING_3 = "PAPER_IS_CREATING_3";
export const FETCH_PAPER = "FETCH_PAPER";
export const PUSH_RANDOM_NUMBER = "PUSH_RANDOM_NUMBER";
export const UPADATE_SINGLE_CHOICE_QUESTION = "UPDATE_SINGLE";
export const UPADATE_MULTIPLE_CHOICE_QUESTION = "UPDATE_MULTIPLE";
export const UPADATE_PARAGRAPH_CHOICE_QUESTION = "UPDATE_PARAGRAPH";
